version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb_ecommerce
    networks:
      - ecommerce_network
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_ecommerce
    networks:
      - ecommerce_network
    links:
      - mongo
    depends_on:
      - mongo
    restart: always
    ports:
      - "8081:8081"
    expose:
      - 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: web:latest
    container_name: backend_ecommerce
    networks:
      - ecommerce_network
    links:
      - mongo
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - app_data:/target/mongodb-shop.jar:/mongodb-shop.jar
    restart: always
    depends_on:
      mongo:
        condition: service_started
volumes:
  mongo_data: {}
  app_data: {}

networks:
  ecommerce_network:
    driver: bridge
