server.port=9000
spring.application.name=mongodb-shop
# database config
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=root
spring.data.mongodb.password=root
spring.data.mongodb.database=ecommerce
spring.data.mongodb.port=27017
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
#for localhost
# spring.data.mongodb.host=localhost
#for deployment
spring.data.mongodb.host=mongo
spring.data.mongodb.auto-index-creation=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#secrets
security.jwt.secret=72357538782F413F4428472B4B6250655368566D597133733676397924422645
security.jwt.expireTime=86400000
